In [ ]:
import pandas as pd
import glob
import os
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd

Mounted at /content/gdrive

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [ ]:
sh=gc.open('tentative')

In [ ]:
ws1=sh.worksheets()

In [ ]:
len(ws1)

11

In [ ]:
ws_calc=sh.worksheet('Forecast calculation')

In [ ]:
type(ws_calc)

gspread.models.Worksheet

In [ ]:
ws_calc_records=ws_calc.get_all_records()

In [ ]:
type(ws_calc_records)

list

In [ ]:
len(ws_calc_records)

42502

In [ ]:
ws1[0]

In [ ]:
ws_im=ws1[0]

In [ ]:
dir(ws_im)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_finder',
 '_properties',
 'acell',
 'add_cols',
 'add_rows',
 'append_row',
 'append_rows',
 'batch_get',
 'batch_update',
 'cell',
 'clear',
 'clear_basic_filter',
 'client',
 'col_count',
 'col_values',
 'delete_row',
 'delete_rows',
 'duplicate',
 'export',
 'find',
 'findall',
 'format',
 'freeze',
 'frozen_col_count',
 'frozen_row_count',
 'get',
 'get_all_records',
 'get_all_values',
 'id',
 'insert_row',
 'merge_cells',
 'range',
 'resize',
 'row_count',
 'row_values',
 'set_basic_filter',
 'sort',
 'spreadsheet',
 'title',
 'update',
 'update_acell',
 'update_cell',
 'update_cells',
 'update_index',
 'update_title',
 'updated',
 'url']

In [ ]:
ws_im.title

'IM latest'

In [ ]:
[item.title for item in ws1]

['IM latest',
 'BOM latest',
 'Forecast details',
 'plan base',
 'Forecast totals',
 'Forecast calculation',
 'PNA cases',
 'LOT',
 'LOT pivot',
 'POT raw',
 'PPC pivot']

In [ ]:
len([item.title for item in ws1])

11

In [ ]:
ws_calc_records

[{'part code': 4902374,
  'model code': 'CMRRMM1066',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'Main PCB',
  'Price': 3461.86,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMRRMM10664902374',
  'Key': 'CMP-REALMEMain PCB',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 9491098,
  'model code': 'CMRRMM1287',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'CAMERA',
  'Price': 542.37,
  'Claims': 13,
  'Cancellation %age': '45%',
  'NRF Landing': 8,
  'Concat': 'CMRRMM12879491098',
  'Key': 'CMP-REALMECAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 17201711,
  'model code': 'CIFIFM1167',
  'PC Brand': 'CMP-INFINIX',
  'Prod Cat': 'CAMERA',
  'Price': 870.97,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CIFIFM116717201711',
  'Key': 'CMP-INFINIXCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 2929170,
  'model code': 'CMRRMM1008',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'Housing',
  'Price': 63.56,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMRRMM10082929170',
  'Key': 'CMP-REALMEHousing',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4906415',
  'model code': 'CMOOPP1172',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 199,
  'Claims': 4,
  'Cancellation %age': '45%',
  'NRF Landing': 3,
  'Concat': 'CMOOPP1172O-4906415',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 17600394,
  'model code': 'CIFIFM1037',
  'PC Brand': 'CMP-INFINIX',
  'Prod Cat': 'SENSOR',
  'Price': 122.23,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CIFIFM103717600394',
  'Key': 'CMP-INFINIXSENSOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 4901712,
  'model code': 'CMRRMM1008',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'Housing',
  'Price': 42.37,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMRRMM10084901712',
  'Key': 'CMP-REALMEHousing',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 4901709,
  'model code': 'CMRRMM1008',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'BATTERY',
  'Price': 423.73,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMRRMM10084901709',
  'Key': 'CMP-REALMEBATTERY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 17600393,
  'model code': 'CIFIFM1039',
  'PC Brand': 'CMP-INFINIX',
  'Prod Cat': 'SENSOR',
  'Price': 122.06,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CIFIFM103917600393',
  'Key': 'CMP-INFINIXSENSOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 9491381,
  'model code': 'CMRRMM1364',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'CAMERA',
  'Price': 540,
  'Claims': 8,
  'Cancellation %age': '45%',
  'NRF Landing': 5,
  'Concat': 'CMRRMM13649491381',
  'Key': 'CMP-REALMECAMERA',
  'PPC': 0.5,
  'Forecast': '',
  'PNA cases': 9491381,
  'New Forecast': ''},
 {'part code': 23503240,
  'model code': 'CIFIFM1066',
  'PC Brand': 'CMP-INFINIX',
  'Prod Cat': 'CONSUMABLE',
  'Price': 7.62,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CIFIFM106623503240',
  'Key': 'CMP-INFINIXCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 4902166,
  'model code': 'CMRRMM1021',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'Main PCB',
  'Price': 1186.44,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMRRMM10214902166',
  'Key': 'CMP-REALMEMain PCB',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903905',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'Main PCB',
  'Price': 6990,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903905',
  'Key': 'CMP-OPPOMain PCB',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903313',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'Display',
  'Price': 3490,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903313',
  'Key': 'CMP-OPPODisplay',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903327',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'BATTERY',
  'Price': 990,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903327',
  'Key': 'CMP-OPPOBATTERY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903323',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 890,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903323',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903322',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 890,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903322',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-5473234',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'ADAPTOR',
  'Price': 450,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-5473234',
  'Key': 'CMP-OPPOADAPTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903318',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'OTHER PCB ASSY',
  'Price': 390,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903318',
  'Key': 'CMP-OPPOOTHER PCB ASSY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-9490946',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 290,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-9490946',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903324',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 290,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903324',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-2930515',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'OTHER PCB ASSY',
  'Price': 290,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-2930515',
  'Key': 'CMP-OPPOOTHER PCB ASSY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-8511181',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'SPEAKER',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-8511181',
  'Key': 'CMP-OPPOSPEAKER',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4965345',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4965345',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903319',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4903319',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-2180553',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-2180553',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-8710152',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'OTHER PCB ASSY',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-8710152',
  'Key': 'CMP-OPPOOTHER PCB ASSY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4965354',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4965354',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4965343',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4965343',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4880849',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4880849',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879365',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4879365',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 3008724,
  'model code': 'CMRRMM1017',
  'PC Brand': 'CMP-REALME',
  'Prod Cat': 'SPARES',
  'Price': 381.36,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMRRMM10173008724',
  'Key': 'CMP-REALMESPARES',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879361',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4879361',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879357',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4879357',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879356',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4879356',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4210695',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-4210695',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-3061561',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-3061561',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-2180863',
  'model code': 'CMOOPP1078',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1078O-2180863',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903905',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'Main PCB',
  'Price': 6990,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903905',
  'Key': 'CMP-OPPOMain PCB',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903313',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'Display',
  'Price': 3490,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903313',
  'Key': 'CMP-OPPODisplay',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903327',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'BATTERY',
  'Price': 990,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903327',
  'Key': 'CMP-OPPOBATTERY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903323',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 890,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903323',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903322',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 890,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903322',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-5473234',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'ADAPTOR',
  'Price': 450,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-5473234',
  'Key': 'CMP-OPPOADAPTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-9180539',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'SENSOR',
  'Price': 390,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-9180539',
  'Key': 'CMP-OPPOSENSOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903318',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'OTHER PCB ASSY',
  'Price': 390,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903318',
  'Key': 'CMP-OPPOOTHER PCB ASSY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-9490946',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 290,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-9490946',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903324',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CAMERA',
  'Price': 290,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903324',
  'Key': 'CMP-OPPOCAMERA',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-2930515',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'OTHER PCB ASSY',
  'Price': 290,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-2930515',
  'Key': 'CMP-OPPOOTHER PCB ASSY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-8511181',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'SPEAKER',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-8511181',
  'Key': 'CMP-OPPOSPEAKER',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4965345',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4965345',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4903319',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4903319',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-2180553',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 190,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-2180553',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-8710152',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'OTHER PCB ASSY',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-8710152',
  'Key': 'CMP-OPPOOTHER PCB ASSY',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4965354',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4965354',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4965343',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'WIRE AND CONNECTOR',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4965343',
  'Key': 'CMP-OPPOWIRE AND CONNECTOR',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4880849',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4880849',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879365',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4879365',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879361',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4879361',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879357',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',
  'NRF Landing': 0,
  'Concat': 'CMOOPP1079O-4879357',
  'Key': 'CMP-OPPOCONSUMABLE',
  'PPC': 0,
  'Forecast': '',
  'PNA cases': 0,
  'New Forecast': ''},
 {'part code': 'O-4879356',
  'model code': 'CMOOPP1079',
  'PC Brand': 'CMP-OPPO',
  'Prod Cat': 'CONSUMABLE',
  'Price': 100,
  'Claims': 0,
  'Cancellation %age': '45%',

In [ ]:
df = pd.DataFrame(ws_calc_records)
df.head()

,part code,model code,PC Brand,Prod Cat,Price,Claims,Cancellation %age,NRF Landing,Concat,Key,PPC,Forecast,PNA cases,New Forecast
0,4902374,CMRRMM1066,CMP-REALME,Main PCB,3461.86,0,45%,0,CMRRMM10664902374,CMP-REALMEMain PCB,0.0,,0,
1,9491098,CMRRMM1287,CMP-REALME,CAMERA,542.37,13,45%,8,CMRRMM12879491098,CMP-REALMECAMERA,0.0,,0,
2,17201711,CIFIFM1167,CMP-INFINIX,CAMERA,870.97,0,45%,0,CIFIFM116717201711,CMP-INFINIXCAMERA,0.0,,0,
3,2929170,CMRRMM1008,CMP-REALME,Housing,63.56,0,45%,0,CMRRMM10082929170,CMP-REALMEHousing,0.0,,0,
4,O-4906415,CMOOPP1172,CMP-OPPO,CONSUMABLE,199.00,4,45%,3,CMOOPP1172O-4906415,CMP-OPPOCONSUMABLE,0.0,,0,

In [ ]:
df['Forecast'] = df['NRF Landing']*df['PPC']
df.head()

,part code,model code,PC Brand,Prod Cat,Price,Claims,Cancellation %age,NRF Landing,Concat,Key,PPC,Forecast,PNA cases,New Forecast
0,4902374,CMRRMM1066,CMP-REALME,Main PCB,3461.86,0,45%,0,CMRRMM10664902374,CMP-REALMEMain PCB,0.0,0.0,0,
1,9491098,CMRRMM1287,CMP-REALME,CAMERA,542.37,13,45%,8,CMRRMM12879491098,CMP-REALMECAMERA,0.0,0.0,0,
2,17201711,CIFIFM1167,CMP-INFINIX,CAMERA,870.97,0,45%,0,CIFIFM116717201711,CMP-INFINIXCAMERA,0.0,0.0,0,
3,2929170,CMRRMM1008,CMP-REALME,Housing,63.56,0,45%,0,CMRRMM10082929170,CMP-REALMEHousing,0.0,0.0,0,
4,O-4906415,CMOOPP1172,CMP-OPPO,CONSUMABLE,199.00,4,45%,3,CMOOPP1172O-4906415,CMP-OPPOCONSUMABLE,0.0,0.0,0,

In [ ]:
import numpy as np
# create a list of our conditions
conditions = [
    (df['PNA cases'] == 0)&(df['Forecast']== 0),
    (df['PNA cases'] == 0)&(df['Forecast']!= 0),
    (df['PNA cases']!= 0)&(df['Forecast']== 0),
    (df['PNA cases']!= 0)&(df['Forecast']!= 0)]

# create a list of the values we want to assign for each condition
values = [df['Forecast'],df['Forecast'],1,df['Forecast']]

# create a new column and use np.select to assign values to it using our lists as arguments
df['New Forecast'] = np.select(conditions, values)
df.head(100)

,part code,model code,PC Brand,Prod Cat,Price,Claims,Cancellation %age,NRF Landing,Concat,Key,PPC,Forecast,PNA cases,New Forecast
0,4902374,CMRRMM1066,CMP-REALME,Main PCB,3461.86,0,45%,0,CMRRMM10664902374,CMP-REALMEMain PCB,0.0,0.0,0,0.0
1,9491098,CMRRMM1287,CMP-REALME,CAMERA,542.37,13,45%,8,CMRRMM12879491098,CMP-REALMECAMERA,0.0,0.0,0,0.0
2,17201711,CIFIFM1167,CMP-INFINIX,CAMERA,870.97,0,45%,0,CIFIFM116717201711,CMP-INFINIXCAMERA,0.0,0.0,0,0.0
3,2929170,CMRRMM1008,CMP-REALME,Housing,63.56,0,45%,0,CMRRMM10082929170,CMP-REALMEHousing,0.0,0.0,0,0.0
4,O-4906415,CMOOPP1172,CMP-OPPO,CONSUMABLE,199.00,4,45%,3,CMOOPP1172O-4906415,CMP-OPPOCONSUMABLE,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4877526,CMRRMM1216,CMP-REALME,CONSUMABLE,50.85,0,45%,0,CMRRMM12164877526,CMP-REALMECONSUMABLE,0.0,0.0,0,0.0
96,4877528,CMRRMM1216,CMP-REALME,CONSUMABLE,15.25,0,45%,0,CMRRMM12164877528,CMP-REALMECONSUMABLE,0.0,0.0,0,0.0
97,4878151,CMRRMM1216,CMP-REALME,CONSUMABLE,1.00,0,45%,0,CMRRMM12164878151,CMP-REALMECONSUMABLE,0.0,0.0,0,0.0
98,4880086,CMRRMM1216,CMP-REALME,CONSUMABLE,15.25,0,45%,0,CMRRMM12164880086,CMP-REALMECONSUMABLE,0.0,0.0,0,0.0
99,4880090,CMRRMM1216,CMP-REALME,CONSUMABLE,15.25,0,45%,0,CMRRMM12164880090,CMP-REALMECONSUMABLE,0.0,0.0,0,0.0

In [ ]:
df['New Forecast'].unique()

array([ 0.        ,  2.5       ,  1.        , 10.5       ,  3.5       ,
        1.16666667,  1.5       ,  3.        ,  1.        ,  2.        ,
        2.14285714,  0.42857143,  8.        ,  2.        ,  4.        ,
        7.        ,  2.33333333,  7.5       ,  3.75      ,  1.66666667,
        9.        ,  1.8       ,  5.4       ,  5.44444444,  0.77777778,
        1.55555556, 26.58333333,  2.41666667,  4.83333333, 14.5       ,
        4.84210526, 38.73684211,  7.26315789, 12.10526316,  9.68421053,
        2.42105263,  1.75      ,  6.        ,  1.25      ,  1.66666667,
        8.66666667,  5.77777778,  2.85714286, 10.        ,  1.42857143,
        2.25      ,  6.75      ,  3.33333333,  5.        ,  4.16666667,
        0.83333333,  8.33333333,  3.33333333,  2.66666667,  6.        ,
        1.        ,  2.        ,  4.        ,  0.5       ,  0.75      ,
        4.66666667,  3.6       ,  1.2       ,  7.2       , 15.        ,
        4.5       , 13.5       ,  1.18181818,  8.27272727,  2.36363636,
        9.45454545,  2.2       ,  3.        ,  8.33333333,  5.        ,
        3.33333333,  9.625     ,  2.75      ,  1.375     ,  6.875     ,
        6.125     ,  0.71428571,  0.875     ,  5.        ,  1.        ,
        1.8       ,  0.6       ,  6.66666666])

In [ ]:
df['New Forecast'].sum()

2476.7113693319898

In [ ]:
import numpy as np
import math
df['Final Forecast']=df['New Forecast'].apply(lambda X: int(math.ceil(X)))
df.head()

,part code,model code,PC Brand,Prod Cat,Price,Claims,Cancellation %age,NRF Landing,Concat,Key,PPC,Forecast,PNA cases,New Forecast,Final Forecast
0,4902374,CMRRMM1066,CMP-REALME,Main PCB,3461.86,0,45%,0,CMRRMM10664902374,CMP-REALMEMain PCB,0.0,0.0,0,0.0,0
1,9491098,CMRRMM1287,CMP-REALME,CAMERA,542.37,13,45%,8,CMRRMM12879491098,CMP-REALMECAMERA,0.0,0.0,0,0.0,0
2,17201711,CIFIFM1167,CMP-INFINIX,CAMERA,870.97,0,45%,0,CIFIFM116717201711,CMP-INFINIXCAMERA,0.0,0.0,0,0.0,0
3,2929170,CMRRMM1008,CMP-REALME,Housing,63.56,0,45%,0,CMRRMM10082929170,CMP-REALMEHousing,0.0,0.0,0,0.0,0
4,O-4906415,CMOOPP1172,CMP-OPPO,CONSUMABLE,199.00,4,45%,3,CMOOPP1172O-4906415,CMP-OPPOCONSUMABLE,0.0,0.0,0,0.0,0

In [ ]:
df['Final Forecast'].sum()

2603

In [ ]:
pivot=df.groupby(['part code','Price','Prod Cat','PC Brand']).agg({'Final Forecast':'sum'})
forecast_pivot = pd.DataFrame(pivot)
forecast_pivot

                                                        Final Forecast
part code         Price  Prod Cat           PC Brand
2180531           200.00 WIRE AND CONNECTOR CMP-REALME               0
2180553           120.76 WIRE AND CONNECTOR CMP-REALME               0
2180579           42.37  WIRE AND CONNECTOR CMP-REALME               0
2180587           21.19  WIRE AND CONNECTOR CMP-REALME               0
2180618           42.37  WIRE AND CONNECTOR CMP-REALME               0
...                                                                ...
SGIMPSPSPRECRE017 100.00 RECEIVER           CMP-GIONEE               0
SGIMPSPSPSPKSP027 100.00 SPEAKER            CMP-GIONEE               0
SGIMPSPSPSPKSP031 100.00 OTHER              CMP-GIONEE               0
SGIMPSPSPSPKSP032 100.00 OTHER              CMP-GIONEE               3
SGIMPSPSPTRYST058 100.00 CONSUMABLE         CMP-GIONEE               0

[6936 rows x 1 columns]

In [ ]:
forecast_pivot['Final Forecast'].sum()

2603

In [ ]:
type(forecast_pivot)

pandas.core.frame.DataFrame

In [ ]:
from google.colab import files
forecast_pivot.to_csv('forecast_pivot.csv')
files.download('forecast_pivot.csv')

In [ ]:
sh2=gc.open('tentative2')

In [ ]:
ws2=sh2.worksheets()
ws2

[<Worksheet 'main working' id:0>,
 <Worksheet 'CDRR data import' id:1655636710>,
 <Worksheet 'SOH raw' id:825315175>,
 <Worksheet 'SOH pivot' id:2056013044>,
 <Worksheet 'CMP PC ALT working' id:2072448866>,
 <Worksheet 'CMP ALT pivot' id:1639267597>,
 <Worksheet 'Alt Base' id:356709697>,
 <Worksheet 'Alt working pivot' id:499290545>]

In [ ]:
ws_main_working=ws2[0]

In [ ]:
ws_main_working.title

'main working'

In [ ]:
[item.title for item in ws2]

['main working',
 'CDRR data import',
 'SOH raw',
 'SOH pivot',
 'CMP PC ALT working',
 'CMP ALT pivot',
 'Alt Base',
 'Alt working pivot']

In [ ]:
ws_main_records=ws_main_working.get_all_records()
ws_main_records

[{'part code': 2180531,
  'Price': 200,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180553,
  'Price': 120.76,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180579,
  'Price': 42.37,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180587,
  'Price': 21.19,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180618,
  'Price': 42.37,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180649,
  'Price': 42.37,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180652,
  'Price': 21.19,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180657,
  'Price': 59.32,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180663,
  'Price': 172.03,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180667,
  'Price': 134.92,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180668,
  'Price': 399,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180669,
  'Price': 270.51,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 1,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180677,
  'Price': 270.51,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180683,
  'Price': 59.32,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180695,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180696,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180712,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180713,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180714,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180743,
  'Price': 270.51,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180780,
  'Price': 134.75,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180785,
  'Price': 199,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180790,
  'Price': 134.92,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180792,
  'Price': 134.92,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180797,
  'Price': 399,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180802,
  'Price': 399,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180813,
  'Price': 399,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180816,
  'Price': 270.51,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180869,
  'Price': 50.85,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180876,
  'Price': 135.59,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 1,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180878,
  'Price': 59.32,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180885,
  'Price': 50.85,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 1,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180886,
  'Price': 50.85,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180887,
  'Price': 50.85,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180908,
  'Price': 270.51,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180920,
  'Price': 270.51,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180989,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 4,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180994,
  'Price': 50.85,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180997,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2180998,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181009,
  'Price': 50.85,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 1,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181012,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 1,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181013,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 2,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181016,
  'Price': 101.69,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181017,
  'Price': 50.85,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 1,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181025,
  'Price': 67.8,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181052,
  'Price': 67.8,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181053,
  'Price': 67.8,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 2,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181083,
  'Price': 67.8,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 1,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181087,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 3,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181088,
  'Price': 50.85,
  'Prod Cat': 'OTHER PCB ASSY',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181092,
  'Price': 67.8,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181093,
  'Price': 67.8,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181105,
  'Price': 135.59,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181106,
  'Price': 135.59,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181114,
  'Price': 50.85,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 10,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181134,
  'Price': 67.8,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181178,
  'Price': 67.8,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181185,
  'Price': 270.34,
  'Prod Cat': 'WIRE AND CONNECTOR',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181196,
  'Price': 399,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181211,
  'Price': 100,
  'Prod Cat': 'SPARES',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,
  'Intransit/Open PO': 0,
  'Requirement': 0,
  'Alt Inv': 0,
  'Procurement Qty': '',
  'Procurement Val': '',
  'SOH Value': '',
  'FDRR Val': ''},
 {'part code': 2181212,
  'Price': 100,
  'Prod Cat': 'CONSUMABLE',
  'PC Brand': 'CMP-REALME',
  'Forecast': 0,
  'FDRR': 0,
  'CDRR': 0,
  'Target Qty': 0,
  'SOH': 0,

In [ ]:
df2 = pd.DataFrame(ws_main_records)
df2.head()

,part code,Price,Prod Cat,PC Brand,Forecast,FDRR,CDRR,Target Qty,SOH,Intransit/Open PO,Requirement,Alt Inv,Procurement Qty,Procurement Val,SOH Value,FDRR Val
0,2180531,200.00,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,,,,
1,2180553,120.76,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,,,,
2,2180579,42.37,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,,,,
3,2180587,21.19,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,,,,
4,2180618,42.37,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,,,,

In [ ]:
df2['Procurement Qty'] = np.maximum(df2['Requirement']-df2['Alt Inv'],0)

In [ ]:
df2['Requirement'].sum()

2735

In [ ]:
df2['Procurement Qty'].sum()

2583

In [ ]:
df2['Procurement Val']=df2['Procurement Qty']*df2['Price']
df2['Procurement Val'].sum()

4797704.15

In [ ]:

df2['SOH Value']=df2['SOH']*df2['Price']
df2['SOH Value'].sum()

6534366.1

In [ ]:
df2['FDRR Val']=df2['FDRR']*df2['Price']
df2['FDRR Val'].sum()

152827.15866303805

In [ ]:
df2.head()

,part code,Price,Prod Cat,PC Brand,Forecast,FDRR,CDRR,Target Qty,SOH,Intransit/Open PO,Requirement,Alt Inv,Procurement Qty,Procurement Val,SOH Value,FDRR Val
0,2180531,200.00,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0
1,2180553,120.76,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0
2,2180579,42.37,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0
3,2180587,21.19,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0
4,2180618,42.37,WIRE AND CONNECTOR,CMP-REALME,0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0

In [ ]:
df2['Procurement Qty'].sum()

2583

In [ ]:
df2['Procurement Val'].sum()

4797704.15

In [ ]:
df3 = df2[df2['Procurement Qty']!=0]
df3.head()

,part code,Price,Prod Cat,PC Brand,Forecast,FDRR,CDRR,Target Qty,SOH,Intransit/Open PO,Requirement,Alt Inv,Procurement Qty,Procurement Val,SOH Value,FDRR Val
229,2932004,67.80,CONSUMABLE,CMP-REALME,4,0.133333,0.035714,6.666667,2,0,5,0,5,339.00,135.60,9.040
254,2932333,67.80,OTHER PCB ASSY,CMP-REALME,3,0.100000,0.000000,5.000000,2,0,3,0,3,203.40,135.60,6.780
297,2933078,67.80,CONSUMABLE,CMP-REALME,3,0.100000,0.035714,5.000000,4,0,1,0,1,67.80,271.20,6.780
298,2933079,67.80,CONSUMABLE,CMP-REALME,6,0.200000,0.071429,10.000000,2,0,8,0,8,542.40,135.60,13.560
403,3052287,338.14,Housing,CMP-REALME,3,0.100000,0.035714,5.000000,4,0,1,0,1,338.14,1352.56,33.814

In [ ]:
pivot3=df3.groupby(['part code']).agg({'Procurement Qty':'sum'})
procurement_pivot = pd.DataFrame(pivot3)
procurement_pivot

                   Procurement Qty
part code
2932004                          5
2932333                          3
2933078                          1
2933079                          8
3052287                          1
...                            ...
SGIMPSPSPCAMCA107                3
SGIMPSPSPHOUBK082                4
SGIMPSPSPOGSLT105                2
SGIMPSPSPPCBSP085                3
SGIMPSPSPSPKSP032                3

[284 rows x 1 columns]

In [ ]:
procurement_pivot['Procurement Qty'].sum()

2583

In [ ]:
from google.colab import files
procurement_pivot.to_csv('procurement_pivot.csv')
files.download('procurement_pivot.csv')

In [ ]:
pivot2=df3.groupby(['PC Brand']).agg({'FDRR Val':'sum','SOH Value':'sum','Procurement Qty':'sum','Procurement Val':'sum'}).reset_index()
summary_pivot = pd.DataFrame(pivot2)
summary_pivot

      PC Brand      FDRR Val   SOH Value  Procurement Qty  Procurement Val
0   CMP-GIONEE    331.051333    11174.04               15          4796.90
1  CMP-INFINIX  19924.460999   172593.79              467        808093.07
2     CMP-OPPO  23360.706332   344647.72              269        794473.59
3   CMP-REALME  88515.871666  1135903.66             1832       3190340.59

In [ ]:
sh3=gc.open('tentative3')

In [ ]:
ws3=sh3.worksheets()
ws3

[<Worksheet 'Main' id:0>,
 <Worksheet 'Returnable Master' id:172772707>,
 <Worksheet 'Plan' id:2101411816>,
 <Worksheet 'forecast pivot' id:1838572471>,
 <Worksheet 'procurement qty' id:73965822>,
 <Worksheet 'IM' id:1039020491>,
 <Worksheet 'Alt BOM' id:130847784>]

In [ ]:
ws_main = ws3[0]
ws_main

In [ ]:
ws_plan=sh3.worksheet('Plan')

In [ ]:
ws_plan_records=ws_plan.get_all_records()
ws_plan_records

[{'F1-Item Code': 2932003,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 5,
  'Price': 67.8,
  'Val': 339,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 2932381,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 5,
  'Price': 67.8,
  'Val': 339,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 2932945,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 67.8,
  'Val': 67.8,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 2933078,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 3,
  'Alt Forecast': 0,
  'Total Forecast': 3,
  'Target': 5,
  'Return': 0,
  'Price': 67.8,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 1},
 {'F1-Item Code': 3052287,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 3,
  'Alt Forecast': 0,
  'Total Forecast': 3,
  'Target': 5,
  'Return': 0,
  'Price': 338.14,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 1},
 {'F1-Item Code': 3052326,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 671.18,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202110,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 5,
  'Price': 929.24,
  'Val': 4646.2,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202354,
  'Returnable': 8,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 8,
  'Price': 1001.27,
  'Val': 8010.16,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202374,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 1001.27,
  'Val': 1001.27,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202392,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 647.58,
  'Val': 647.58,
  'Brand': 'CMP-REALME',
  'Plan': 1},
 {'F1-Item Code': 3202412,
  'Returnable': 7,
  'Alt': 0,
  'PC Forecast': 3,
  'Alt Forecast': 0,
  'Total Forecast': 3,
  'Target': 5,
  'Return': 2,
  'Price': 425.43,
  'Val': 850.86,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202416,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 3,
  'Price': 425.43,
  'Val': 1276.29,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202420,
  'Returnable': 12,
  'Alt': 0,
  'PC Forecast': 3,
  'Alt Forecast': 0,
  'Total Forecast': 3,
  'Target': 5,
  'Return': 7,
  'Price': 577.37,
  'Val': 4041.59,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202422,
  'Returnable': 7,
  'Alt': 4906556,
  'PC Forecast': 4,
  'Alt Forecast': 0,
  'Total Forecast': 4,
  'Target': 7,
  'Return': 0,
  'Price': 577.38,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202466,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 942.37,
  'Val': 1884.74,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3202547,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 5,
  'Alt Forecast': 0,
  'Total Forecast': 5,
  'Target': 9,
  'Return': 0,
  'Price': 713.14,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 7},
 {'F1-Item Code': 3202762,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 3,
  'Price': 942.37,
  'Val': 2827.11,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3203005,
  'Returnable': 4,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 671.18,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 2},
 {'F1-Item Code': 3203466,
  'Returnable': 7,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 3,
  'Price': 671.19,
  'Val': 2013.57,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3203486,
  'Returnable': 4,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 4,
  'Price': 671.19,
  'Val': 2684.76,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3203488,
  'Returnable': 16,
  'Alt': 0,
  'PC Forecast': 1,
  'Alt Forecast': 0,
  'Total Forecast': 1,
  'Target': 2,
  'Return': 14,
  'Price': 671.19,
  'Val': 9396.66,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3203752,
  'Returnable': 4,
  'Alt': 0,
  'PC Forecast': 3,
  'Alt Forecast': 0,
  'Total Forecast': 3,
  'Target': 5,
  'Return': 0,
  'Price': 270.34,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 3204173,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 5,
  'Alt Forecast': 0,
  'Total Forecast': 5,
  'Target': 9,
  'Return': 0,
  'Price': 372.03,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 4},
 {'F1-Item Code': 3204438,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 4,
  'Alt Forecast': 0,
  'Total Forecast': 4,
  'Target': 7,
  'Return': 0,
  'Price': 990,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 5},
 {'F1-Item Code': 3204539,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 671.19,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4100003,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 3,
  'Price': 6451.69,
  'Val': 19355.07,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4100190,
  'Returnable': 1,
  'Alt': 4100233,
  'PC Forecast': 4,
  'Alt Forecast': 0,
  'Total Forecast': 4,
  'Target': 7,
  'Return': 0,
  'Price': 11490,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 1},
 {'F1-Item Code': 4130050,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 8,
  'Alt Forecast': 0,
  'Total Forecast': 8,
  'Target': 14,
  'Return': 0,
  'Price': 3312.71,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 8},
 {'F1-Item Code': 4130052,
  'Returnable': 6,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 6,
  'Price': 3398.13,
  'Val': 20388.78,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4130057,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 14,
  'Alt Forecast': 0,
  'Total Forecast': 14,
  'Target': 24,
  'Return': 0,
  'Price': 2664.41,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4130167,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 8,
  'Alt Forecast': 0,
  'Total Forecast': 8,
  'Target': 14,
  'Return': 0,
  'Price': 3306.78,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 9},
 {'F1-Item Code': 4170024,
  'Returnable': 4,
  'Alt': 0,
  'PC Forecast': 7,
  'Alt Forecast': 0,
  'Total Forecast': 7,
  'Target': 12,
  'Return': 0,
  'Price': 2027.12,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 4},
 {'F1-Item Code': 4180010,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 467.8,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4190072,
  'Returnable': 6,
  'Alt': 0,
  'PC Forecast': 5,
  'Alt Forecast': 0,
  'Total Forecast': 5,
  'Target': 9,
  'Return': 0,
  'Price': 203.39,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 2},
 {'F1-Item Code': 4190203,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 203.39,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4190204,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 203.39,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4200013,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 3,
  'Price': 1800,
  'Val': 5400,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4816077,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 405.93,
  'Val': 405.93,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4816078,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 2099,
  'Val': 2099,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4816088,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 19.49,
  'Val': 38.98,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4882907,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 4,
  'Alt Forecast': 0,
  'Total Forecast': 4,
  'Target': 7,
  'Return': 0,
  'Price': 15.25,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 1},
 {'F1-Item Code': 4883531,
  'Returnable': 21,
  'Alt': 4883530,
  'PC Forecast': 18,
  'Alt Forecast': 0,
  'Total Forecast': 18,
  'Target': 30,
  'Return': 0,
  'Price': 15.25,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 12},
 {'F1-Item Code': 4885217,
  'Returnable': 38,
  'Alt': 0,
  'PC Forecast': 17,
  'Alt Forecast': 0,
  'Total Forecast': 17,
  'Target': 29,
  'Return': 9,
  'Price': 15.25,
  'Val': 137.25,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4885219,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 18,
  'Alt Forecast': 0,
  'Total Forecast': 18,
  'Target': 30,
  'Return': 0,
  'Price': 15.25,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 9},
 {'F1-Item Code': 4885774,
  'Returnable': 18,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 18,
  'Price': 0.01,
  'Val': 0.18,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4885776,
  'Returnable': 8,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 8,
  'Price': 0.01,
  'Val': 0.08,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4886004,
  'Returnable': 33,
  'Alt': 0,
  'PC Forecast': 19,
  'Alt Forecast': 0,
  'Total Forecast': 19,
  'Target': 32,
  'Return': 1,
  'Price': 15.25,
  'Val': 15.25,
  'Brand': 'CMP-REALME',
  'Plan': 2},
 {'F1-Item Code': 4886543,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 6,
  'Alt Forecast': 0,
  'Total Forecast': 6,
  'Target': 10,
  'Return': 0,
  'Price': 15.25,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 7},
 {'F1-Item Code': 4886911,
  'Returnable': 31,
  'Alt': 0,
  'PC Forecast': 20,
  'Alt Forecast': 0,
  'Total Forecast': 20,
  'Target': 34,
  'Return': 0,
  'Price': 0.01,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 13},
 {'F1-Item Code': 4888013,
  'Returnable': 7,
  'Alt': 0,
  'PC Forecast': 48,
  'Alt Forecast': 0,
  'Total Forecast': 48,
  'Target': 80,
  'Return': 0,
  'Price': 15.25,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 71},
 {'F1-Item Code': 4888228,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 21,
  'Alt Forecast': 0,
  'Total Forecast': 21,
  'Target': 35,
  'Return': 0,
  'Price': 29.66,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 25},
 {'F1-Item Code': 4888640,
  'Returnable': 13,
  'Alt': 0,
  'PC Forecast': 6,
  'Alt Forecast': 0,
  'Total Forecast': 6,
  'Target': 10,
  'Return': 3,
  'Price': 15.25,
  'Val': 45.75,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4888821,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 29.66,
  'Val': 59.32,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4888966,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 8,
  'Alt Forecast': 0,
  'Total Forecast': 8,
  'Target': 14,
  'Return': 0,
  'Price': 15.26,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 7},
 {'F1-Item Code': 4889406,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 37,
  'Alt Forecast': 0,
  'Total Forecast': 37,
  'Target': 62,
  'Return': 0,
  'Price': 15.25,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 37},
 {'F1-Item Code': 4890093,
  'Returnable': 6,
  'Alt': 0,
  'PC Forecast': 7,
  'Alt Forecast': 0,
  'Total Forecast': 7,
  'Target': 12,
  'Return': 0,
  'Price': 15.26,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 8},
 {'F1-Item Code': 4891724,
  'Returnable': 16,
  'Alt': 0,
  'PC Forecast': 16,
  'Alt Forecast': 0,
  'Total Forecast': 16,
  'Target': 27,
  'Return': 0,
  'Price': 15.25,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 13},
 {'F1-Item Code': 4902729,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 720.34,
  'Val': 1440.68,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4904747,
  'Returnable': 5,
  'Alt': 4909261,
  'PC Forecast': 4,
  'Alt Forecast': 0,
  'Total Forecast': 4,
  'Target': 7,
  'Return': 0,
  'Price': 3234.32,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4904760,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 1555.93,
  'Val': 3111.86,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4904769,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 264.41,
  'Val': 528.82,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4904835,
  'Returnable': 1,
  'Alt': 4908456,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 713.14,
  'Val': 713.14,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4905057,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 10,
  'Alt Forecast': 0,
  'Total Forecast': 10,
  'Target': 17,
  'Return': 0,
  'Price': 671.19,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 12},
 {'F1-Item Code': 4905232,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 4,
  'Alt Forecast': 0,
  'Total Forecast': 4,
  'Target': 7,
  'Return': 0,
  'Price': 1073.72,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 4},
 {'F1-Item Code': 4905691,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 3,
  'Price': 203.38,
  'Val': 610.14,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4905923,
  'Returnable': 8,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 8,
  'Price': 8754.75,
  'Val': 70038,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4905926,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 3,
  'Price': 271.19,
  'Val': 813.57,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4905928,
  'Returnable': 7,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 7,
  'Price': 713.13,
  'Val': 4991.91,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4905936,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 972.46,
  'Val': 1944.92,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906056,
  'Returnable': 3,
  'Alt': 4906154,
  'PC Forecast': 6,
  'Alt Forecast': 0,
  'Total Forecast': 6,
  'Target': 10,
  'Return': 0,
  'Price': 1749.78,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906079,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 6,
  'Alt Forecast': 0,
  'Total Forecast': 6,
  'Target': 10,
  'Return': 0,
  'Price': 237.29,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906081,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 7,
  'Alt Forecast': 0,
  'Total Forecast': 7,
  'Target': 12,
  'Return': 0,
  'Price': 338.31,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 6},
 {'F1-Item Code': 4906082,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 243.46,
  'Val': 243.46,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906084,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 350.08,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906180,
  'Returnable': 1,
  'Alt': 4906459,
  'PC Forecast': 12,
  'Alt Forecast': 0,
  'Total Forecast': 12,
  'Target': 20,
  'Return': 0,
  'Price': 3168.64,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906181,
  'Returnable': 1,
  'Alt': 4906184,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 5575.42,
  'Val': 5575.42,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906183,
  'Returnable': 3,
  'Alt': 4906186,
  'PC Forecast': 2,
  'Alt Forecast': 0,
  'Total Forecast': 2,
  'Target': 4,
  'Return': 0,
  'Price': 6372.03,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 1},
 {'F1-Item Code': 4906206,
  'Returnable': 3,
  'Alt': 0,
  'PC Forecast': 8,
  'Alt Forecast': 0,
  'Total Forecast': 8,
  'Target': 14,
  'Return': 0,
  'Price': 203.39,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 8},
 {'F1-Item Code': 4906281,
  'Returnable': 1,
  'Alt': 4906283,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 4453.05,
  'Val': 4453.05,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906283,
  'Returnable': 2,
  'Alt': 4906281,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 4007.74,
  'Val': 8015.48,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906341,
  'Returnable': 7,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 7,
  'Price': 296.6,
  'Val': 2076.2,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906343,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 575.55,
  'Val': 575.55,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906459,
  'Returnable': 22,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 22,
  'Price': 3168.64,
  'Val': 69710.08,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906460,
  'Returnable': 5,
  'Alt': 0,
  'PC Forecast': 11,
  'Alt Forecast': 0,
  'Total Forecast': 11,
  'Target': 19,
  'Return': 0,
  'Price': 203.39,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 13},
 {'F1-Item Code': 4906634,
  'Returnable': 3,
  'Alt': 4907143,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 3,
  'Price': 4103.39,
  'Val': 12310.17,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906644,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 1,
  'Price': 264.41,
  'Val': 264.41,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906662,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 17,
  'Alt Forecast': 0,
  'Total Forecast': 17,
  'Target': 29,
  'Return': 0,
  'Price': 3234.32,
  'Val': 0,
  'Brand': 'CMP-REALME',
  'Plan': 15},
 {'F1-Item Code': 4906681,
  'Returnable': 2,
  'Alt': 0,
  'PC Forecast': 0,
  'Alt Forecast': 0,
  'Total Forecast': 0,
  'Target': 0,
  'Return': 2,
  'Price': 6881.99,
  'Val': 13763.98,
  'Brand': 'CMP-REALME',
  'Plan': 0},
 {'F1-Item Code': 4906683,
  'Returnable': 1,
  'Alt': 0,
  'PC Forecast': 19,

In [ ]:
df4 = pd.DataFrame(ws_plan_records)
df4.head()

,F1-Item Code,Returnable,Alt,PC Forecast,Alt Forecast,Total Forecast,Target,Return,Price,Val,Brand,Plan
0,2932003,5,0,0,0,0,0,5,67.80,339.0,CMP-REALME,0
1,2932381,5,0,0,0,0,0,5,67.80,339.0,CMP-REALME,0
2,2932945,1,0,0,0,0,0,1,67.80,67.8,CMP-REALME,0
3,2933078,1,0,3,0,3,5,0,67.80,0.0,CMP-REALME,1
4,3052287,2,0,3,0,3,5,0,338.14,0.0,CMP-REALME,1

In [ ]:
df5 = df4[df4['Plan']==0]
df5.head()

,F1-Item Code,Returnable,Alt,PC Forecast,Alt Forecast,Total Forecast,Target,Return,Price,Val,Brand,Plan
0,2932003,5,0,0,0,0,0,5,67.80,339.0,CMP-REALME,0
1,2932381,5,0,0,0,0,0,5,67.80,339.0,CMP-REALME,0
2,2932945,1,0,0,0,0,0,1,67.80,67.8,CMP-REALME,0
5,3052326,3,0,2,0,2,4,0,671.18,0.0,CMP-REALME,0
6,3202110,5,0,0,0,0,0,5,929.24,4646.2,CMP-REALME,0

In [ ]:
df5['Plan'].sum()

0

In [ ]:
df5['Return'].sum()

903

In [ ]:
df6 = df5[df5['Return']!=0]
df6.head()

,F1-Item Code,Returnable,Alt,PC Forecast,Alt Forecast,Total Forecast,Target,Return,Price,Val,Brand,Plan
0,2932003,5,0,0,0,0,0,5,67.80,339.00,CMP-REALME,0
1,2932381,5,0,0,0,0,0,5,67.80,339.00,CMP-REALME,0
2,2932945,1,0,0,0,0,0,1,67.80,67.80,CMP-REALME,0
6,3202110,5,0,0,0,0,0,5,929.24,4646.20,CMP-REALME,0
7,3202354,8,0,0,0,0,0,8,1001.27,8010.16,CMP-REALME,0

In [ ]:
df6['Return'].sum()

903

In [ ]:
pivot4=df6.groupby(['F1-Item Code']).agg({'Return':'sum'})
return_pivot = pd.DataFrame(pivot4)
return_pivot

                   Return
F1-Item Code
2932003                 5
2932381                 5
2932945                 1
3202110                 5
3202354                 8
...                   ...
O-9561245               5
SGIMPSPSPCAMCA093       1
SGIMPSPSPPCBMP075       2
SGIMPSPSPPCBMP079       3
SGIMPSPSPRECRE017       2

[199 rows x 1 columns]

In [ ]:
return_pivot['Return'].sum()

903

In [ ]:
from google.colab import files
return_pivot.to_csv('return_pivot.csv')
files.download('return_pivot.csv')

In [ ]:
pivot5=df6.groupby(['Brand']).agg({'Val':'sum'})
return_summary = pd.DataFrame(pivot5)
return_summary

                   Val
Brand
CMP-GIONEE    14121.28
CMP-INFINIX  381437.13
CMP-OPPO     321082.46
CMP-REALME   818071.15

In [ ]:
return_summary['Val'].sum()

1534712.02